"""Build assets/js/lessons-python.js and verify every runnable code block.
Run from anywhere:  python3 tools/lessons/build_lessons.py
"""
import json, os, subprocess, sys, tempfile
here = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, here)
import part1, part2
L = part1.LESSONS
OUT = os.path.join(here, "..", "..", "assets", "js", "lessons-python.js")

def run(code, cwd):
    r = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True, cwd=cwd, timeout=10)
    return r.stdout.rstrip("\n"), r.stderr
bad = 0
for les in L:
    with tempfile.TemporaryDirectory() as d:
        for b in les["blocks"]:
            if b.get("noRun"): continue
            # blocks flagged needs_prev read files made by the previous block
            out, err = run(b["code"], d)
            exp = b["output"].rstrip("\n")
            if out.strip() != exp.strip():
                bad += 1; print("MISMATCH", les["id"], b["title"]); print(" expected:", repr(exp)); print(" got     :", repr(out), err[-200:])
        t = les["tryit"]
        with tempfile.TemporaryDirectory() as d2:
            out, err = run(t["solution"], d2)
            if out.strip() != t["output"].strip():
                bad += 1; print("TRY MISMATCH", les["id"]); print(" expected:", repr(t["output"])); print(" got     :", repr(out), err[-200:])
print("lessons:", len(L), "problems:", bad)
if bad: sys.exit(1)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/lessons/build_lessons.py\nwindow.PYDSA_LESSONS = " + json.dumps(L, ensure_ascii=False) + ";\n")
