"""Rebuild assets/js/data.js from the program folders in tools/source_programs.
Run:  python3 tools/build_data.py
Add a new program: drop the .py file + a line in that folder's Index.txt, then re-run.
"""
import json, os, re

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "source_programs")
OUT = os.path.join(ROOT, "..", "assets", "js", "data.js")

# folder number -> (slug, label, accent, default difficulty, blurb)
GROUPS = {
 1:  ("arrays-strings",   "Arrays & Strings",            "blue",   "easy",   "The warm-up round: loops over lists and strings."),
 2:  ("arrays-strings-2", "Arrays & Strings · Part 2",   "blue",   "easy",   "More array and string basics, plus linear search."),
 3:  ("recursion-math",   "Recursion & Math",            "purple", "easy",   "Functions that call themselves, plus GCD, LCM and powers."),
 4:  ("searching-sorting","Searching & Sorting",         "teal",   "medium", "Linear/binary search and the classic sorting algorithms."),
 5:  ("linked-list",      "Linked List",                 "teal",   "medium", "Nodes, pointers, insert, delete and search."),
 6:  ("stack-queue",      "Stack & Queue",               "teal",   "easy",   "LIFO and FIFO built with arrays and linked lists."),
 7:  ("stack-queue-adv",  "Stack & Queue · Advanced",    "teal",   "medium", "Classic interview tricks using stacks and queues."),
 8:  ("dynamic-programming","Dynamic Programming",       "purple", "medium", "Remember sub-answers instead of recomputing them."),
 9:  ("bit-manipulation", "Bit Manipulation",            "purple", "medium", "Work directly with the 0s and 1s of a number."),
 10: ("patterns",         "Pattern Printing",            "orange", "easy",   "Nested loops that draw shapes. Great for loop logic."),
}

# (folder, program) -> difficulty overrides
DIFF = {
 (1,"05.1"):"easy",(1,"05.2"):"medium",(1,"06"):"easy",(1,"10"):"easy",
 (4,"01"):"easy",(4,"02"):"easy",(4,"03"):"medium",(4,"04"):"easy",(4,"05"):"easy",(4,"06"):"easy",
 (4,"07"):"medium",(4,"08"):"medium",(4,"09"):"hard",(4,"10"):"medium",
 (5,"01"):"easy",(5,"02"):"easy",(5,"03"):"easy",(5,"08"):"easy",(5,"09"):"easy",
 (6,"05"):"medium",(6,"06"):"hard",(7,"01"):"medium",(7,"02"):"medium",(7,"03"):"medium",(7,"04"):"medium",
 (8,"01"):"easy",(8,"02"):"hard",(8,"03"):"hard",(8,"04"):"medium",(8,"05"):"medium",(8,"06"):"hard",
 (8,"07"):"hard",(8,"08"):"medium",(8,"09"):"medium",(8,"10"):"medium",
 (9,"01"):"easy",(9,"02"):"easy",(9,"03"):"easy",(9,"04"):"easy",(9,"05"):"easy",(9,"06"):"medium",
 (9,"07"):"easy",(9,"08"):"medium",(9,"09"):"medium",(9,"10"):"hard",
 (10,"07"):"medium",(10,"08"):"medium",
}

# Same idea in more than one folder. These related programs can be shown together as several approaches.
TOPICS = {
 "reverse-array":["1-02","2-02"], "reverse-string":["1-08","2-08"],
 "palindrome-string":["1-03","2-10"], "count-occurrences":["1-04","2-06"],
 "factorial":["1-09","3-01","3-10"],
}
TOPIC_OF = {k:t for t,ks in TOPICS.items() for k in ks}

def clean_title(t):
    t = re.sub(r"\s+(systematically|objectives)$","",t.strip(), flags=re.I)
    t = t.replace("occurances","Occurrences").replace("Check if a string is a palindrome","Check if a String is a Palindrome")
    return t[0].upper()+t[1:]

programs = []
for folder in sorted(os.listdir(SRC), key=lambda f:int(f.split(" ")[0])):
    n = int(folder.split(" ")[0]); slug,label,accent,dd,blurb = GROUPS[n]
    idx = open(os.path.join(SRC,folder,"Index.txt"),encoding="utf-8").read()
    for line in idx.splitlines():
        m = re.match(r"\s*Program\s+([\d.]+)\s*:\s*(.+)",line)
        if not m: continue
        num, title = m.group(1), clean_title(m.group(2))
        fn = os.path.join(SRC,folder,num.lstrip("0").replace(".0",".0")+".py")
        base = str(int(num.split(".")[0])) + ("."+num.split(".")[1] if "." in num else "")
        fn = os.path.join(SRC,folder,base+".py")
        code = open(fn,encoding="utf-8").read().replace("\r\n","\n").strip("\n") if os.path.exists(fn) else ""
        key = f"{n}-{num.split('.')[0]}" if "." not in num else f"{n}-{num.split('.')[0]}"
        pid = f"{slug}-{num.replace('.','-')}"
        programs.append({
          "id":pid,"group":slug,"n":num,"title":title,
          "difficulty":DIFF.get((n,num), dd),
          "topic":TOPIC_OF.get(f"{n}-{num.split('.')[0]}") if "." not in num else None,
          "code":code})

groups = [{"slug":v[0],"label":v[1],"accent":v[2],"blurb":v[4],
           "count":sum(1 for p in programs if p["group"]==v[0])} for k,v in sorted(GROUPS.items())]

with open(OUT,"w",encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/build_data.py — do not edit by hand.\n")
    f.write("window.PYDSA_PROGRAMS = "+json.dumps(programs,ensure_ascii=False)+";\n")
    f.write("window.PYDSA_GROUPS = "+json.dumps(groups,ensure_ascii=False)+";\n")
print(len(programs),"programs,",len(groups),"groups ->",os.path.normpath(OUT))
missing=[p["id"] for p in programs if not p["code"]]
print("missing code:",missing)
